# Generated by Django 3.2.5 on 2021-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='img_url',
            field=models.URLField(default='', verbose_name='Image url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='info',
            field=models.TextField(default='url', verbose_name='Information.'),
            preserve_default=False,
        ),
    ]
